version: '2'

services:
  copybara:
    image: sharelatex/copybara
    volumes:
      - ./.ssh:/root/.ssh
      - .:/usr/src/app
      - ./.cache/:/root/copybara/cache/
      - $HOME/.gitconfig:/root/.gitconfig
    # Uncomment this to force copybara to start syncing from a certain commit
    # environment:
    #   COPYBARA_OPTIONS: "--last-rev=67edeed2c2d8c1d478c9a65d19020a301174cc8e"
    command: copybara